runtime: nodejs
service: be-strapi

env: flex

env_variables:
  NODE_ENV: 'production'
  DATABASE_NAME: 'growfi-strapi-uat'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'pxjBmHIAvccO9IB7'
  DATABASE_HOST: '/cloudsql/growfi-test:asia-southeast1:temp-only-less'
  APP_KEYS: 'Q7gyGU5LoBb+1yubeTFNfg==,PAISIdm0AWGpVNzcWpue6g==,G1mjXMK5G+pJX5z4bkJ70A==,Oa6SApHVfPkBYv/6wBqUvg=='
  API_TOKEN_SALT: 'yCKEWM9jWIsZarSuQRkBaw=='
  ADMIN_JWT_SECRET: 'rrmwK/aqjsvooTKRi30Sgg=='
  JWT_SECRET: 'v1n68lJBd+eOKAcyMQ0w0w=='

beta_settings:
  cloud_sql_instances: 'growfi-test:asia-southeast1:temp-only-less'
