runtime: nodejs

env: flex

env_variables:
  HOST: '34.124.186.149'
  NODE_ENV: 'production'
  DATABASE_NAME: 'growfi-strapi-uat'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'pxjBmHIAvccO9IB7'
  INSTANCE_CONNECTION_NAME: '<instance_identifier>'

beta_settings:
  cloud_sql_instances: '<instance_identifier>'